import type { BackgroundPreset, GradientLayer } from "./types";

export const INITIAL_LAYERS: GradientLayer[] = [
  {
    id: "1",
    type: "radial",
    color: "#ffffff",
    x: 30,
    y: 40,
    width: 80,
    height: 80,
    opacity: 1,
    blur: 100,
    speed: 1,
    blendMode: "overlay",
    rotation: 0,
    animation: "float",
    animationSpeed: 0.2,
    visible: true,
    repeatInfinity: true,
  },
  {
    id: "2",
    type: "radial",
    color: "#cbd5e1",
    x: 70,
    y: 60,
    width: 70,
    height: 70,
    opacity: 0.8,
    blur: 80,
    speed: 1,
    blendMode: "multiply",
    rotation: 0,
    animation: "breathe",
    animationSpeed: 0.3,
    visible: true,
    repeatInfinity: true,
  },
];

export const DEFAULT_BG_START = "#f8fafc";
export const DEFAULT_BG_END = "#e2e8f0";

export const BACKGROUND_PRESETS: Record<string, BackgroundPreset> = {
  aurora: {
    name: "Aurora Dream",
    emoji: "",
    bgStart: "#f8fafc",
    bgEnd: "#e2e8f0",
    bgAngle: 180,
    layers: INITIAL_LAYERS,
    noiseOpacity: 0.2,
    pattern: "none",
    patternOpacity: 0.1,
    patternColor: "#000000",
    vignette: 0.05,
    saturation: 90,
  },
  lavender: {
    name: "Lavender Blush",
    emoji: "",
    bgStart: "#E1BEE7",
    bgEnd: "#FFF0F5",
    bgAngle: 135,
    layers: [
      {
        id: "l1",
        type: "radial",
        color: "rgba(255, 182, 193, 0.4)",
        x: 20,
        y: 30,
        width: 60,
        height: 60,
        opacity: 1,
        blur: 60,
        speed: 0.8,
        blendMode: "multiply",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.5,
        visible: true,
      },
      {
        id: "l2",
        type: "radial",
        color: "rgba(221, 160, 221, 0.5)",
        x: 80,
        y: 60,
        width: 50,
        height: 50,
        opacity: 1,
        blur: 50,
        speed: -0.6,
        blendMode: "multiply",
        rotation: 0,
        animation: "breathe",
        animationSpeed: 0.4,
        visible: true,
      },
      {
        id: "l3",
        type: "mesh",
        color: "rgba(216, 191, 216, 0.6)",
        secondaryColor: "rgba(255, 228, 225, 0.4)",
        x: 50,
        y: 50,
        width: 80,
        height: 80,
        opacity: 0.7,
        blur: 70,
        speed: 0.4,
        blendMode: "overlay",
        rotation: 0,
        animation: "none",
        animationSpeed: 1,
        visible: true,
      },
    ],
    noiseOpacity: 0.1,
    pattern: "dots",
    patternOpacity: 0.05,
    patternColor: "#E1BEE7",
    vignette: 0.15,
    saturation: 100,
  },
  midnight: {
    name: "Midnight Galaxy",
    emoji: "",
    bgStart: "#0f172a",
    bgEnd: "#1e1b4b",
    bgAngle: 180,
    layers: [
      {
        id: "m1",
        type: "radial",
        color: "rgba(99, 102, 241, 0.3)",
        x: 20,
        y: 30,
        width: 50,
        height: 50,
        opacity: 1,
        blur: 40,
        speed: 1.2,
        blendMode: "screen",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.6,
        visible: true,
      },
      {
        id: "m2",
        type: "radial",
        color: "rgba(167, 139, 250, 0.2)",
        x: 70,
        y: 60,
        width: 60,
        height: 60,
        opacity: 1,
        blur: 50,
        speed: -0.8,
        blendMode: "screen",
        rotation: 0,
        animation: "pulse",
        animationSpeed: 0.4,
        visible: true,
      },
      {
        id: "m3",
        type: "conic",
        color: "rgba(79, 70, 229, 0.15)",
        x: 50,
        y: 50,
        width: 100,
        height: 100,
        opacity: 0.5,
        blur: 60,
        speed: 0.2,
        blendMode: "overlay",
        rotation: 0,
        animation: "breathe",
        animationSpeed: 0.4,
        visible: true,
      },
    ],
    noiseOpacity: 0.2,
    pattern: "grid",
    patternOpacity: 0.05,
    patternColor: "#6366f1",
    vignette: 0.3,
    saturation: 100,
  },
  sunset: {
    name: "Sunset Glow",
    emoji: "",
    bgStart: "#fff7ed",
    bgEnd: "#ffedd5",
    bgAngle: 180,
    layers: [
      {
        id: "s1",
        type: "radial",
        color: "rgba(253, 186, 116, 0.6)",
        x: 10,
        y: 20,
        width: 80,
        height: 80,
        opacity: 1,
        blur: 80,
        speed: 0.6,
        blendMode: "multiply",
        rotation: 0,
        animation: "breathe",
        animationSpeed: 0.3,
        visible: true,
      },
      {
        id: "s2",
        type: "radial",
        color: "rgba(251, 146, 60, 0.5)",
        x: 80,
        y: 30,
        width: 60,
        height: 60,
        opacity: 1,
        blur: 60,
        speed: -0.4,
        blendMode: "multiply",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.4,
        visible: true,
      },
      {
        id: "s3",
        type: "linear",
        color: "rgba(244, 63, 94, 0.3)",
        secondaryColor: "rgba(251, 191, 36, 0.2)",
        x: 50,
        y: 80,
        width: 100,
        height: 50,
        opacity: 0.8,
        blur: 50,
        speed: 0.3,
        blendMode: "overlay",
        rotation: 0,
        animation: "none",
        animationSpeed: 1,
        visible: true,
      },
    ],
    noiseOpacity: 0.1,
    pattern: "none",
    patternOpacity: 0,
    patternColor: "#000000",
    vignette: 0.2,
    saturation: 110,
  },
  ocean: {
    name: "Tropical Ocean",
    emoji: "",
    bgStart: "#ecfeff",
    bgEnd: "#cffafe",
    bgAngle: 180,
    layers: [
      {
        id: "o1",
        type: "radial",
        color: "rgba(45, 212, 191, 0.4)",
        x: 20,
        y: 80,
        width: 70,
        height: 70,
        opacity: 1,
        blur: 70,
        speed: 1.0,
        blendMode: "multiply",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.5,
        visible: true,
      },
      {
        id: "o2",
        type: "radial",
        color: "rgba(34, 211, 238, 0.5)",
        x: 75,
        y: 25,
        width: 55,
        height: 55,
        opacity: 1,
        blur: 55,
        speed: -0.7,
        blendMode: "multiply",
        rotation: 0,
        animation: "breathe",
        animationSpeed: 0.4,
        visible: true,
      },
      {
        id: "o3",
        type: "mesh",
        color: "rgba(6, 182, 212, 0.4)",
        secondaryColor: "rgba(94, 234, 212, 0.3)",
        x: 50,
        y: 50,
        width: 90,
        height: 90,
        opacity: 0.8,
        blur: 80,
        speed: 0.4,
        blendMode: "overlay",
        rotation: 0,
        animation: "none",
        animationSpeed: 1,
        visible: true,
      },
    ],
    noiseOpacity: 0.15,
    pattern: "waves",
    patternOpacity: 0.08,
    patternColor: "#0891b2",
    vignette: 0.1,
    saturation: 100,
  },
  neon: {
    name: "Neon Nights",
    emoji: "",
    bgStart: "#09090b",
    bgEnd: "#18181b",
    bgAngle: 180,
    layers: [
      {
        id: "n1",
        type: "conic",
        color: "#d946ef",
        x: 20,
        y: 20,
        width: 100,
        height: 100,
        opacity: 0.15,
        blur: 80,
        speed: 0.5,
        blendMode: "screen",
        rotation: 0,
        animation: "rotate",
        animationSpeed: 0.1,
        visible: true,
      },
      {
        id: "n2",
        type: "radial",
        color: "rgba(217, 70, 239, 0.3)",
        x: 80,
        y: 70,
        width: 50,
        height: 50,
        opacity: 1,
        blur: 50,
        speed: -1.0,
        blendMode: "screen",
        rotation: 0,
        animation: "pulse",
        animationSpeed: 0.8,
        visible: true,
      },
      {
        id: "n3",
        type: "radial",
        color: "rgba(6, 182, 212, 0.2)",
        x: 30,
        y: 70,
        width: 40,
        height: 40,
        opacity: 1,
        blur: 40,
        speed: 0.8,
        blendMode: "screen",
        rotation: 0,
        animation: "pulse",
        animationSpeed: 0.8,
        visible: true,
      },
    ],
    noiseOpacity: 0.15,
    pattern: "circuit",
    patternOpacity: 0.1,
    patternColor: "#d946ef",
    vignette: 0.4,
    saturation: 120,
  },
  candy: {
    name: "Candy Crush",
    emoji: "",
    bgStart: "#fdf4ff",
    bgEnd: "#fae8ff",
    bgAngle: 135,
    layers: [
      {
        id: "c1",
        type: "radial",
        color: "#f472b6",
        x: 10,
        y: 90,
        width: 60,
        height: 60,
        opacity: 0.4,
        blur: 50,
        speed: 0.8,
        blendMode: "multiply",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.6,
        visible: true,
      },
      {
        id: "c2",
        type: "radial",
        color: "#a78bfa",
        x: 90,
        y: 15,
        width: 50,
        height: 50,
        opacity: 0.35,
        blur: 45,
        speed: -0.6,
        blendMode: "multiply",
        rotation: 0,
        animation: "pulse",
        animationSpeed: 0.5,
        visible: true,
      },
      {
        id: "c3",
        type: "radial",
        color: "#38bdf8",
        x: 50,
        y: 50,
        width: 70,
        height: 70,
        opacity: 0.3,
        blur: 60,
        speed: 0.4,
        blendMode: "overlay",
        rotation: 0,
        animation: "breathe",
        animationSpeed: 0.5,
        visible: true,
      },
    ],
    noiseOpacity: 0.1,
    pattern: "dots",
    patternOpacity: 0.15,
    patternColor: "#f472b6",
    vignette: 0,
    saturation: 100,
  },
  cloud: {
    name: "Soft Cloud",
    emoji: "",
    bgStart: "#f8fafc",
    bgEnd: "#e2e8f0",
    bgAngle: 180,
    layers: [
      {
        id: "cl1",
        type: "radial",
        color: "#ffffff",
        x: 30,
        y: 40,
        width: 80,
        height: 80,
        opacity: 1,
        blur: 100,
        speed: 1,
        blendMode: "overlay",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.2,
        visible: true,
      },
      {
        id: "cl2",
        type: "radial",
        color: "#cbd5e1",
        x: 70,
        y: 60,
        width: 70,
        height: 70,
        opacity: 0.8,
        blur: 80,
        speed: 1,
        blendMode: "multiply",
        rotation: 0,
        animation: "breathe",
        animationSpeed: 0.3,
        visible: true,
      },
    ],
    noiseOpacity: 0.2,
    pattern: "none",
    patternOpacity: 0,
    patternColor: "#000000",
    vignette: 0.05,
    saturation: 90,
  },
  forest: {
    name: "Enchanted Forest",
    emoji: "",
    bgStart: "#022c22",
    bgEnd: "#064e3b",
    bgAngle: 180,
    layers: [
      {
        id: "f1",
        type: "radial",
        color: "rgba(34, 197, 94, 0.3)",
        x: 30,
        y: 70,
        width: 60,
        height: 60,
        opacity: 1,
        blur: 50,
        speed: 0.7,
        blendMode: "screen",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.4,
        visible: true,
      },
      {
        id: "f2",
        type: "radial",
        color: "rgba(74, 222, 128, 0.25)",
        x: 75,
        y: 30,
        width: 50,
        height: 50,
        opacity: 1,
        blur: 40,
        speed: -0.5,
        blendMode: "screen",
        rotation: 0,
        animation: "breathe",
        animationSpeed: 0.5,
        visible: true,
      },
      {
        id: "f3",
        type: "conic",
        color: "rgba(16, 185, 129, 0.15)",
        x: 50,
        y: 50,
        width: 80,
        height: 80,
        opacity: 0.8,
        blur: 70,
        speed: 0.2,
        blendMode: "overlay",
        rotation: 0,
        animation: "rotate",
        animationSpeed: 0.1,
        visible: true,
      },
    ],
    noiseOpacity: 0.25,
    pattern: "hexagon",
    patternOpacity: 0.05,
    patternColor: "#22c55e",
    vignette: 0.35,
    saturation: 100,
  },
  fire: {
    name: "Phoenix Fire",
    emoji: "",
    bgStart: "#1c1917",
    bgEnd: "#292524",
    bgAngle: 180,
    layers: [
      {
        id: "fi1",
        type: "radial",
        color: "rgba(239, 68, 68, 0.5)",
        x: 50,
        y: 80,
        width: 80,
        height: 80,
        opacity: 1,
        blur: 70,
        speed: 1.5,
        blendMode: "screen",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.8,
        visible: true,
      },
      {
        id: "fi2",
        type: "radial",
        color: "rgba(251, 146, 60, 0.4)",
        x: 30,
        y: 50,
        width: 50,
        height: 50,
        opacity: 1,
        blur: 50,
        speed: -1.0,
        blendMode: "screen",
        rotation: 0,
        animation: "pulse",
        animationSpeed: 1.2,
        visible: true,
      },
      {
        id: "fi3",
        type: "radial",
        color: "rgba(250, 204, 21, 0.3)",
        x: 60,
        y: 40,
        width: 40,
        height: 40,
        opacity: 1,
        blur: 40,
        speed: 1.2,
        blendMode: "screen",
        rotation: 0,
        animation: "pulse",
        animationSpeed: 1.5,
        visible: true,
      },
    ],
    noiseOpacity: 0.2,
    pattern: "none",
    patternOpacity: 0,
    patternColor: "#000000",
    vignette: 0.5,
    saturation: 130,
  },
  ice: {
    name: "Frozen Ice",
    emoji: "",
    bgStart: "#f0f9ff",
    bgEnd: "#e0f2fe",
    bgAngle: 180,
    layers: [
      {
        id: "i1",
        type: "radial",
        color: "rgba(56, 189, 248, 0.3)",
        x: 20,
        y: 30,
        width: 60,
        height: 60,
        opacity: 1,
        blur: 70,
        speed: 0.6,
        blendMode: "multiply",
        rotation: 0,
        animation: "breathe",
        animationSpeed: 0.4,
        visible: true,
      },
      {
        id: "i2",
        type: "radial",
        color: "rgba(147, 197, 253, 0.4)",
        x: 80,
        y: 70,
        width: 60,
        height: 60,
        opacity: 1,
        blur: 60,
        speed: -0.4,
        blendMode: "multiply",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.3,
        visible: true,
      },
      {
        id: "i3",
        type: "mesh",
        color: "rgba(224, 242, 254, 0.6)",
        secondaryColor: "rgba(186, 230, 253, 0.4)",
        x: 50,
        y: 50,
        width: 100,
        height: 100,
        opacity: 0.8,
        blur: 80,
        speed: 0.2,
        blendMode: "overlay",
        rotation: 0,
        animation: "none",
        animationSpeed: 1,
        visible: true,
      },
    ],
    noiseOpacity: 0.15,
    pattern: "hexagon",
    patternOpacity: 0.08,
    patternColor: "#38bdf8",
    vignette: 0.1,
    saturation: 100,
  },
  cosmic: {
    name: "Cosmic Dust",
    emoji: "",
    bgStart: "#0c0a09",
    bgEnd: "#1c1917",
    bgAngle: 180,
    layers: [
      {
        id: "co1",
        type: "radial",
        color: "rgba(192, 132, 252, 0.2)",
        x: 20,
        y: 20,
        width: 50,
        height: 50,
        opacity: 1,
        blur: 40,
        speed: 1.0,
        blendMode: "screen",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.5,
        visible: true,
      },
      {
        id: "co2",
        type: "radial",
        color: "rgba(244, 114, 182, 0.15)",
        x: 80,
        y: 30,
        width: 40,
        height: 40,
        opacity: 1,
        blur: 30,
        speed: -1.2,
        blendMode: "screen",
        rotation: 0,
        animation: "pulse",
        animationSpeed: 0.8,
        visible: true,
      },
      {
        id: "co3",
        type: "radial",
        color: "rgba(251, 191, 36, 0.1)",
        x: 60,
        y: 70,
        width: 30,
        height: 30,
        opacity: 1,
        blur: 20,
        speed: 0.8,
        blendMode: "screen",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.6,
        visible: true,
      },
      {
        id: "co4",
        type: "conic",
        color: "rgba(139, 92, 246, 0.1)",
        x: 50,
        y: 50,
        width: 120,
        height: 120,
        opacity: 1,
        blur: 100,
        speed: 0.3,
        blendMode: "overlay",
        rotation: 0,
        animation: "rotate",
        animationSpeed: 0.05,
        visible: true,
      },
    ],
    noiseOpacity: 0.3,
    pattern: "none",
    patternOpacity: 0,
    patternColor: "#000000",
    vignette: 0.5,
    saturation: 110,
  },
  minimal: {
    name: "Clean Minimal",
    emoji: "",
    bgStart: "#fafafa",
    bgEnd: "#f5f5f5",
    bgAngle: 180,
    layers: [
      {
        id: "mi1",
        type: "radial",
        color: "rgba(0, 0, 0, 0.02)",
        x: 80,
        y: 20,
        width: 60,
        height: 60,
        opacity: 1,
        blur: 60,
        speed: 0.3,
        blendMode: "multiply",
        rotation: 0,
        animation: "none",
        animationSpeed: 1,
        visible: true,
      },
      {
        id: "mi2",
        type: "radial",
        color: "rgba(0, 0, 0, 0.02)",
        x: 20,
        y: 80,
        width: 50,
        height: 50,
        opacity: 1,
        blur: 50,
        speed: -0.3,
        blendMode: "multiply",
        rotation: 0,
        animation: "none",
        animationSpeed: 1,
        visible: true,
      },
    ],
    noiseOpacity: 0.03,
    pattern: "grid",
    patternOpacity: 0.03,
    patternColor: "#a3a3a3",
    vignette: 0,
    saturation: 100,
  },
  gradient: {
    name: "Mesh Gradient",
    emoji: "",
    bgStart: "#fef3c7",
    bgEnd: "#fce7f3",
    bgAngle: 135,
    layers: [
      {
        id: "mg1",
        type: "mesh",
        color: "rgba(251, 146, 60, 0.5)",
        secondaryColor: "rgba(244, 114, 182, 0.5)",
        x: 30,
        y: 30,
        width: 80,
        height: 80,
        opacity: 1,
        blur: 80,
        speed: 0.8,
        blendMode: "multiply",
        rotation: 0,
        animation: "float",
        animationSpeed: 0.4,
        visible: true,
      },
      {
        id: "mg2",
        type: "mesh",
        color: "rgba(52, 211, 153, 0.4)",
        secondaryColor: "rgba(96, 165, 250, 0.4)",
        x: 70,
        y: 70,
        width: 70,
        height: 70,
        opacity: 1,
        blur: 70,
        speed: -0.6,
        blendMode: "multiply",
        rotation: 0,
        animation: "breathe",
        animationSpeed: 0.5,
        visible: true,
      },
      {
        id: "mg3",
        type: "radial",
        color: "rgba(167, 139, 250, 0.3)",
        x: 50,
        y: 50,
        width: 90,
        height: 90,
        opacity: 1,
        blur: 90,
        speed: 0.4,
        blendMode: "overlay",
        rotation: 0,
        animation: "none",
        animationSpeed: 1,
        visible: true,
      },
    ],
    noiseOpacity: 0.08,
    pattern: "none",
    patternOpacity: 0,
    patternColor: "#000000",
    vignette: 0.15,
    saturation: 100,
  },
};
